### ISSUE TITLE
Don't associate tag with entity

### ISSUE THREAD

**Issue by bobman38** [fogs/tagging-bundle#25]
Running on Symfony2.8.18
I have followed the guide to setup my tagging system on an entity named Question
I have added the right thing to the Question form

But when I enter any tag it is not saved ? (tag not saved and nothing in tagging)

Thanks for help :)

**Comment by bobman38** [comment]
Okay I have also fixed this issue by putting the

<script src="{{ asset('js/tagging-bundle.js') }}"></script>

at the end of the page not in the head section :) It is a good day with 2 issues fixed :)

I close that !

**Comment by fogs** [comment]
I have changed the README slightly, hoping to make it clearer for folks to come..
